language: python

matrix:
    include:
        - os: linux
          python: 3.5.2
          env: NOXSESSION=tests-3.5.2
        - os: linux
          python: 3.5.3
          env: NOXSESSION=tests-3.5.3
        - os: linux
          python: 3.5
          env: NOXSESSION=tests-3.5
        - os: linux
          python: 3.6
          env: NOXSESSION=tests-3.6
        - os: linux
          python: 3.7
          dist: xenial
          env: NOXSESSION=tests-3.7
        - os: linux
          python: 3.8
          dist: xenial
          env: NOXSESSION=tests-3.8
        - os: linux
          python: 3.9-dev
          dist: xenial
          env: NOXSESSION=tests-3.9
        - os: linux
          python: 3.7
          env: NOXSESSION=docs
#        # Warning: Don't try to use code coverage analysis with pypy as it is insanely slow
#        - os: linux
#          python: pypy3
#          env: TOXENV=pypy3
#        # Latest Python 3.x from Homebrew
#        - os: osx
#          language: generic
#          env:
#            - TOXENV=py36
#            - BREW_INSTALL=python3

install:
  - if [[ $TRAVIS_PYTHON_VERSION == 3.5.2 ]]; then pip install nox==2019.11.9 pre-commit; else pip install nox pre-commit; fi
#  - |
#    if [[ $TRAVIS_OS_NAME == 'osx' ]]; then
#      if [[ -n "$BREW_INSTALL" ]]; then
#        brew update
#        brew install "$BREW_INSTALL"
#      fi
#    fi

before_script:
  # stop the build if there are Python syntax errors or undefined names
  # exit-zero treats all errors as warnings.  The GitHub editor is 127 chars wide
  # Reads from setup.cfg for configuration options.
  if [[ $NOXSESSION == tests-3.8 ]]; then
    pre-commit run -a;
  fi

script:
  - echo "$NOXSESSION"; nox --non-interactive --session "$NOXSESSION"
